ARTICLES_TABLES = 'articles'
ARTICLES_ID_COLUMN = 'id'
ARTICLES_NAME_COLUMN = 'name'

AGENTS_TABLE = 'agents'
AGENTS_ID_COLUMN = 'id'
AGENTS_NAME_COLUMN = 'name'

ACCESS_TABLE = 'access_methods'
ACCESS_ID_COLUMN = 'id'
ACCESS_NAME_COLUMN = 'name'

GRANULARITY_TABLE = 'granularity'
GRANULARITY_ID_COLUMN = 'id'
GRANULARITY_NAME_COLUMN = 'name'

PAGE_VIEWS_TABLE = 'pageviews'
